In [40]:
!git clone https://github.com/abecode/teaching_reviews.git

fatal: destination path 'teaching_reviews' already exists and is not an empty directory.


In [41]:
!cp /content/teaching_reviews/data_prodigy/prodigy.sentence-level.20240701.db /content/
!cp /content/teaching_reviews/data_prodigy/prodigy.sentence-level.20240605.db /content/

In [42]:
!ls /content/

prodigy.sentence-level.20240605.db  sample_data
prodigy.sentence-level.20240701.db  teaching_reviews


In [43]:
import sqlite3

db_path = '/content/prodigy.sentence-level.20240701.db'


In [44]:
conn = sqlite3.connect(db_path)

In [45]:
sakthi_annotations = conn.execute("""select dataset.id, dataset.name, dataset.created, dataset.meta, dataset.session,
                                        example.id, example.input_hash, example.task_hash, example.content
                                 from dataset, example, link
                                 where dataset.id = link.dataset_id
                                   and link.example_id = example.id
                                   and dataset.name = 'teaching_reviews_sentences-sakthi';""").fetchall()

In [46]:
len(sakthi_annotations)

725

In [47]:
jenny_annotations = conn.execute("""select dataset.id, dataset.name, dataset.created, dataset.meta, dataset.session,
                                        example.id, example.input_hash, example.task_hash, example.content
                                 from dataset, example, link
                                 where dataset.id = link.dataset_id
                                   and link.example_id = example.id
                                   and dataset.name = 'teaching_reviews_sentences-jenny';""").fetchall()


In [48]:
len(jenny_annotations)

725

In [49]:
abe_annotations = conn.execute("""select dataset.id, dataset.name, dataset.created, dataset.meta, dataset.session,
                                        example.id, example.input_hash, example.task_hash, example.content
                                 from dataset, example, link
                                 where dataset.id = link.dataset_id
                                   and link.example_id = example.id
                                   and dataset.name = 'teaching_reviews_sentences-abe';""").fetchall()


In [50]:
len(abe_annotations)

725

In [51]:
mengyuan_annotations = conn.execute("""select dataset.id, dataset.name, dataset.created, dataset.meta, dataset.session,
                                        example.id, example.input_hash, example.task_hash, example.content
                                 from dataset, example, link
                                 where dataset.id = link.dataset_id
                                   and link.example_id = example.id
                                   and dataset.name = 'teaching_reviews_sentences-mengyuan';""").fetchall()

In [52]:
len(mengyuan_annotations)

725

In [53]:
input_hashes = [];
task_hashes = [];
for annotation in sakthi_annotations:
  input_hashes.append(annotation[5])
  task_hashes.append(annotation[6])
for annotation in jenny_annotations:
  input_hashes.append(annotation[5])
  task_hashes.append(annotation[6])

In [54]:
print(len(input_hashes))
print(len(task_hashes))
print(len(set(input_hashes)))
print(len(set(task_hashes)))

1450
1450
1450
725


In [55]:
import pandas as pd
import json
import numpy as np

In [56]:
sakthi_anno_df = pd.DataFrame({"annotator": ["sakthi" for x in sakthi_annotations],
                           "input_hash": [x[5] for x in sakthi_annotations],
                           "task_hash": [x[6] for x in sakthi_annotations],
                           #"content": [x[8] for x in sakthi_annotations],
                           "text": [json.loads(x[8])['text'] for x in sakthi_annotations],
                           "annotation":  [json.loads(x[8])['accept'] for x in sakthi_annotations]})

In [57]:
jenny_anno_df = pd.DataFrame({"annotator": ["jenny" for x in jenny_annotations],
                           "input_hash": [x[5] for x in jenny_annotations],
                           "task_hash": [x[6] for x in jenny_annotations],
                           #"content": [x[8] for x in jenny_annotations],
                           "text": [json.loads(x[8])['text'] for x in jenny_annotations],
                           "annotation":  [json.loads(x[8])['accept'] for x in jenny_annotations]})

In [58]:
abe_anno_df = pd.DataFrame({"annotator": ["abe" for x in abe_annotations],
                           "input_hash": [x[5] for x in abe_annotations],
                           "task_hash": [x[6] for x in abe_annotations],
                           #"content": [x[8] for x in abe_annotations],
                           "text": [json.loads(x[8])['text'] for x in abe_annotations],
                           "annotation":  [json.loads(x[8])['accept'] for x in abe_annotations]})

In [59]:

mengyuan_anno_df = pd.DataFrame({"annotator": ["mengyuan" for x in mengyuan_annotations],
                           "input_hash": [x[5] for x in mengyuan_annotations],
                           "task_hash": [x[6] for x in mengyuan_annotations],
                           #"content": [x[8] for x in mengyuan_annotations],
                           "text": [json.loads(x[8])['text'] for x in mengyuan_annotations],
                           "annotation":  [json.loads(x[8])['accept'] for x in mengyuan_annotations]})

**Pick first label**

In [60]:
sakthi_anno_df_first_label = pd.DataFrame({
    "annotator": ["sakthi" for x in sakthi_annotations],
    "annotation": [json.loads(x[8])['accept'][0] if json.loads(x[8])['accept'] else None for x in sakthi_annotations]
})

jenny_anno_df_first_label = pd.DataFrame({
    "annotator": ["jenny" for x in jenny_annotations],
    "annotation": [json.loads(x[8])['accept'][0] if json.loads(x[8])['accept'] else None for x in jenny_annotations]
})

abe_anno_df_first_label = pd.DataFrame({
    "annotator": ["abe" for x in abe_annotations],
    "annotation": [json.loads(x[8])['accept'][0] if json.loads(x[8])['accept'] else None for x in abe_annotations]
})

mengyuan_anno_df_first_label = pd.DataFrame({
    "annotator": ["mengyuan" for x in mengyuan_annotations],
    "annotation": [json.loads(x[8])['accept'][0] if json.loads(x[8])['accept'] else None for x in mengyuan_annotations]
})

**Merge 4 df**

In [61]:
merged_df_first_label = pd.DataFrame({
    "sakthi_annotation": sakthi_anno_df_first_label["annotation"],
    "jenny_annotation": jenny_anno_df_first_label["annotation"],
    "abe_annotation": abe_anno_df_first_label["annotation"],
    "mengyuan_annotation": mengyuan_anno_df_first_label["annotation"]
}).dropna()  # Drop rows with None values if any
merged_df_first_label

sakthi_annotation jenny_annotation abe_annotation mengyuan_annotation
0            POSITIVE         POSITIVE       POSITIVE            POSITIVE
1          SUGGESTION       SUGGESTION          MIXED          SUGGESTION
2            POSITIVE         POSITIVE       POSITIVE            POSITIVE
3            POSITIVE         POSITIVE       POSITIVE            POSITIVE
4            POSITIVE         POSITIVE       POSITIVE            POSITIVE
..                ...              ...            ...                 ...
720          POSITIVE         POSITIVE       POSITIVE            POSITIVE
721          POSITIVE         POSITIVE       POSITIVE            POSITIVE
722        SUGGESTION            MIXED       NEGATIVE          SUGGESTION
723           NEUTRAL       SUGGESTION     SUGGESTION            POSITIVE
724           NEUTRAL         NEGATIVE       NEGATIVE            NEGATIVE

[724 rows x 4 columns]

**Define Label Maping**

In [62]:
label_mapping = {
    'POSITIVE': 0,
    'NEGATIVE': 1,
    'NEUTRAL': 2,
    'SUGGESTION': 3,
    'MIXED': 4,
    'UNSURE': 5
}
def map_labels(label):
    return label_mapping.get(label, -1)
df_numeric = merged_df_first_label.applymap(map_labels)

**Get statistic table**

In [63]:
n_categories = len(label_mapping)
counts = np.zeros((len(df_numeric), n_categories))

for i in range(len(df_numeric)):
    counts[i] = np.bincount(df_numeric.iloc[i], minlength=n_categories)

print(counts)

[[4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 1. 0.]
 [4. 0. 0. 0. 0. 0.]
 ...
 [0. 1. 0. 2. 1. 0.]
 [1. 0. 1. 2. 0. 0.]
 [0. 3. 1. 0. 0. 0.]]


In [64]:
from statsmodels.stats.inter_rater import fleiss_kappa

kappa = fleiss_kappa(counts)
print(f'Fleiss\' kappa for the fist label: {kappa}')

Fleiss' kappa for the fist label: 0.6473087366235425


**Fleiss\' kappa value Reference**

< 0	Poor agreement

0.01 – 0.20	Slight agreement

0.21 – 0.40	Fair agreement

0.41 – 0.60	Moderate agreement

0.61 – 0.80	Substantial agreement

0.81 – 1.00	Almost perfect agreement

In [65]:
# function to pick the single main label
def get_main_label(labels):
  if len(labels) == 1:
    return labels[0]
  elif "UNSURE" in labels:
    return "UNSURE"
  elif None in labels: # this may be something to double check
    return "UNSURE"
  elif labels == None:
    return "UNSURE"
  elif "MIXED" in labels:
    return "MIXED"
  elif len(labels) > 1:
    return "MIXED"
  raise Exception("No main label found")

In [66]:
sakthi_anno_df_main_label = pd.DataFrame({
    "annotator": ["sakthi" for x in sakthi_annotations],
    "annotation": [get_main_label(json.loads(x[8])['accept']) if json.loads(x[8])['accept'] else None for x in sakthi_annotations]
})

jenny_anno_df_main_label = pd.DataFrame({
    "annotator": ["jenny" for x in jenny_annotations],
    "annotation": [get_main_label(json.loads(x[8])['accept']) if json.loads(x[8])['accept'] else None for x in jenny_annotations]
})

In [67]:
mengyuan_anno_df_main_label = pd.DataFrame({
    "annotator": ["mengyuan" for x in mengyuan_annotations],
    "annotation": [get_main_label(json.loads(x[8])['accept']) if json.loads(x[8])['accept'] else None for x in mengyuan_annotations]
})
#mengyuan_anno_df_main_label['annotation'] = mengyuan_anno_df_main_label['annotation'].fillna("UNSURE")
abe_anno_df_main_label = pd.DataFrame({
    "annotator": ["abe" for x in abe_annotations],
    "annotation": [get_main_label(json.loads(x[8])['accept']) if json.loads(x[8])['accept'] else None for x in abe_annotations]
})

In [68]:
none_indices = mengyuan_anno_df_main_label[mengyuan_anno_df_main_label['annotation'].isnull()].index

print("Indices of rows with None values in 'annotation' column:")
print(none_indices.tolist())
mengyuan_anno_df_main_label['annotation'] = mengyuan_anno_df_main_label['annotation'].fillna("UNSURE")

Indices of rows with None values in 'annotation' column:
[77]


In [69]:
for label in mengyuan_anno_df_main_label['annotation']:
  if label not in set(["UNSURE", "MIXED", "POSITIVE", "NEGATIVE", "NEUTRAL", "SUGGESTION"]):
     print(label)

In [70]:
merged_df_main_label = pd.DataFrame({
    "sakthi_annotation": sakthi_anno_df_main_label["annotation"],
    "jenny_annotation": jenny_anno_df_main_label["annotation"],
    "abe_annotation": abe_anno_df_main_label["annotation"],
    "mengyuan_annotation": mengyuan_anno_df_main_label["annotation"]
}).dropna()  # Drop rows with None values if any
merged_df_main_label

sakthi_annotation jenny_annotation abe_annotation mengyuan_annotation
0            POSITIVE         POSITIVE       POSITIVE            POSITIVE
1          SUGGESTION            MIXED          MIXED          SUGGESTION
2            POSITIVE         POSITIVE       POSITIVE            POSITIVE
3            POSITIVE         POSITIVE       POSITIVE            POSITIVE
4            POSITIVE         POSITIVE       POSITIVE            POSITIVE
..                ...              ...            ...                 ...
720          POSITIVE         POSITIVE       POSITIVE            POSITIVE
721          POSITIVE         POSITIVE       POSITIVE            POSITIVE
722        SUGGESTION            MIXED          MIXED          SUGGESTION
723           NEUTRAL       SUGGESTION     SUGGESTION            POSITIVE
724           NEUTRAL         NEGATIVE       NEGATIVE            NEGATIVE

[725 rows x 4 columns]

In [71]:
label_mapping2 = {
    'POSITIVE': 0,
    'NEGATIVE': 1,
    'NEUTRAL': 2,
    'SUGGESTION': 3,
    'MIXED': 4,
    'UNSURE': 5
}
def map_labels(label):
    return label_mapping2.get(label, -1)
df_numeric2 = merged_df_main_label.applymap(map_labels)

In [72]:
n_categories = len(label_mapping2)
counts = np.zeros((len(df_numeric2), n_categories))

for i in range(len(df_numeric2)):
    counts[i] = np.bincount(df_numeric2.iloc[i], minlength=n_categories)

print(counts)

[[4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 2. 0.]
 [4. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 2. 2. 0.]
 [1. 0. 1. 2. 0. 0.]
 [0. 3. 1. 0. 0. 0.]]


In [73]:
kappa2 = fleiss_kappa(counts)
print(f'Fleiss\' kappa for the fist label: {kappa2}')

Fleiss' kappa for the fist label: 0.6450134938452556
